apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfatah-echo-ingress
  namespace: alfatah-eks-activity
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "alfatah-echoapp.sctp-sandbox.com"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "alfatah-echoapp.sctp-sandbox.com"
      secretName: alfatah-echoapp-tls
  rules:
    - host: "alfatah-echoapp.sctp-sandbox.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alfatah-echo-service
                port:
                  number: 80
